#######################################
# additional include directories
include_directories(
  ${fftwroot}/api
  ${fftwroot}/dft
  ${fftwroot}/dft/scalar
  ${fftwroot}/dft/simd
  ${fftwroot}/kernel
  ${fftwroot}/rdft
  ${fftwroot}/rdft/scalar
  ${fftwroot}/rdft/simd
  ${fftwroot}/reodft
  ${fftwroot}/simd-support
  ${fftwroot}/threads
  )
#######################################
# library sources
set(cmake_srcs
  ${fftwroot}/cmake/libfftw.cmake
  ${fftwroot}/cmake/config.h.cmake
  ${fftwroot}/cmake/config.h.in
  )
source_group(cmake FILES ${cmake_srcs})
list(APPEND ${lib_name}_libsrcs ${cmake_srcs})
########################
# api
set(api_srcs
  ${fftwroot}/api/apiplan.c
  ${fftwroot}/api/configure.c
  ${fftwroot}/api/execute-dft-c2r.c
  ${fftwroot}/api/execute-dft-r2c.c
  ${fftwroot}/api/execute-dft.c
  ${fftwroot}/api/execute-r2r.c
  ${fftwroot}/api/execute-split-dft-c2r.c
  ${fftwroot}/api/execute-split-dft-r2c.c
  ${fftwroot}/api/execute-split-dft.c
  ${fftwroot}/api/execute.c
  ${fftwroot}/api/export-wisdom-to-file.c
  ${fftwroot}/api/export-wisdom-to-string.c
  ${fftwroot}/api/export-wisdom.c
  ${fftwroot}/api/f77api.c
  ${fftwroot}/api/flops.c
  ${fftwroot}/api/forget-wisdom.c
  ${fftwroot}/api/import-system-wisdom.c
  ${fftwroot}/api/import-wisdom-from-file.c
  ${fftwroot}/api/import-wisdom-from-string.c
  ${fftwroot}/api/import-wisdom.c
  ${fftwroot}/api/malloc.c
  ${fftwroot}/api/map-r2r-kind.c
  ${fftwroot}/api/mapflags.c
  ${fftwroot}/api/mkprinter-file.c
  ${fftwroot}/api/mktensor-iodims.c
  ${fftwroot}/api/mktensor-iodims64.c
  ${fftwroot}/api/mktensor-rowmajor.c
  ${fftwroot}/api/plan-dft-1d.c
  ${fftwroot}/api/plan-dft-2d.c
  ${fftwroot}/api/plan-dft-3d.c
  ${fftwroot}/api/plan-dft-c2r-1d.c
  ${fftwroot}/api/plan-dft-c2r-2d.c
  ${fftwroot}/api/plan-dft-c2r-3d.c
  ${fftwroot}/api/plan-dft-c2r.c
  ${fftwroot}/api/plan-dft-r2c-1d.c
  ${fftwroot}/api/plan-dft-r2c-2d.c
  ${fftwroot}/api/plan-dft-r2c-3d.c
  ${fftwroot}/api/plan-dft-r2c.c
  ${fftwroot}/api/plan-dft.c
  ${fftwroot}/api/plan-guru-dft-c2r.c
  ${fftwroot}/api/plan-guru-dft-r2c.c
  ${fftwroot}/api/plan-guru-dft.c
  ${fftwroot}/api/plan-guru-r2r.c
  ${fftwroot}/api/plan-guru-split-dft-c2r.c
  ${fftwroot}/api/plan-guru-split-dft-r2c.c
  ${fftwroot}/api/plan-guru-split-dft.c
  ${fftwroot}/api/plan-guru64-dft-c2r.c
  ${fftwroot}/api/plan-guru64-dft-r2c.c
  ${fftwroot}/api/plan-guru64-dft.c
  ${fftwroot}/api/plan-guru64-r2r.c
  ${fftwroot}/api/plan-guru64-split-dft-c2r.c
  ${fftwroot}/api/plan-guru64-split-dft-r2c.c
  ${fftwroot}/api/plan-guru64-split-dft.c
  ${fftwroot}/api/plan-many-dft-c2r.c
  ${fftwroot}/api/plan-many-dft-r2c.c
  ${fftwroot}/api/plan-many-dft.c
  ${fftwroot}/api/plan-many-r2r.c
  ${fftwroot}/api/plan-r2r-1d.c
  ${fftwroot}/api/plan-r2r-2d.c
  ${fftwroot}/api/plan-r2r-3d.c
  ${fftwroot}/api/plan-r2r.c
  ${fftwroot}/api/print-plan.c
  ${fftwroot}/api/rdft2-pad.c
  ${fftwroot}/api/the-planner.c
  ${fftwroot}/api/version.c
  )
source_group("Source Files\\api" FILES ${api_srcs})
list(APPEND ${lib_name}_libsrcs ${api_srcs})
########################
# dft
set(dft_srcs
  ${fftwroot}/dft/bluestein.c
  ${fftwroot}/dft/buffered.c
  ${fftwroot}/dft/conf.c
  ${fftwroot}/dft/ct.c
  ${fftwroot}/dft/dftw-direct.c
  ${fftwroot}/dft/dftw-directsq.c
  ${fftwroot}/dft/dftw-generic.c
  ${fftwroot}/dft/dftw-genericbuf.c
  ${fftwroot}/dft/direct.c
  ${fftwroot}/dft/generic.c
  ${fftwroot}/dft/indirect-transpose.c
  ${fftwroot}/dft/indirect.c
  ${fftwroot}/dft/kdft-dif.c
  ${fftwroot}/dft/kdft-difsq.c
  ${fftwroot}/dft/kdft-dit.c
  ${fftwroot}/dft/kdft.c
  ${fftwroot}/dft/nop.c
  ${fftwroot}/dft/plan.c
  ${fftwroot}/dft/problem.c
  ${fftwroot}/dft/rader.c
  ${fftwroot}/dft/rank-geq2.c
  ${fftwroot}/dft/solve.c
  ${fftwroot}/dft/vrank-geq1.c
  ${fftwroot}/dft/zero.c
  )
source_group("Source Files\\dft" FILES ${dft_srcs})
list(APPEND ${lib_name}_libsrcs ${dft_srcs})
#####
set(dft_scalar_srcs
  ${fftwroot}/dft/scalar/n.c
  ${fftwroot}/dft/scalar/t.c
  )
source_group("Source Files\\dft\\scalar" FILES ${dft_scalar_srcs})
list(APPEND ${lib_name}_libsrcs ${dft_scalar_srcs})
#####
set(dft_scalar_codelets_srcs
  ${fftwroot}/dft/scalar/codelets/codlist.c
  ${fftwroot}/dft/scalar/codelets/n1_10.c
  ${fftwroot}/dft/scalar/codelets/n1_11.c
  ${fftwroot}/dft/scalar/codelets/n1_12.c
  ${fftwroot}/dft/scalar/codelets/n1_13.c
  ${fftwroot}/dft/scalar/codelets/n1_14.c
  ${fftwroot}/dft/scalar/codelets/n1_15.c
  ${fftwroot}/dft/scalar/codelets/n1_16.c
  ${fftwroot}/dft/scalar/codelets/n1_2.c
  ${fftwroot}/dft/scalar/codelets/n1_20.c
  ${fftwroot}/dft/scalar/codelets/n1_25.c
  ${fftwroot}/dft/scalar/codelets/n1_3.c
  ${fftwroot}/dft/scalar/codelets/n1_32.c
  ${fftwroot}/dft/scalar/codelets/n1_4.c
  ${fftwroot}/dft/scalar/codelets/n1_5.c
  ${fftwroot}/dft/scalar/codelets/n1_6.c
  ${fftwroot}/dft/scalar/codelets/n1_64.c
  ${fftwroot}/dft/scalar/codelets/n1_7.c
  ${fftwroot}/dft/scalar/codelets/n1_8.c
  ${fftwroot}/dft/scalar/codelets/n1_9.c
  ${fftwroot}/dft/scalar/codelets/q1_2.c
  ${fftwroot}/dft/scalar/codelets/q1_3.c
  ${fftwroot}/dft/scalar/codelets/q1_4.c
  ${fftwroot}/dft/scalar/codelets/q1_5.c
  ${fftwroot}/dft/scalar/codelets/q1_6.c
  ${fftwroot}/dft/scalar/codelets/q1_8.c
  ${fftwroot}/dft/scalar/codelets/t1_10.c
  ${fftwroot}/dft/scalar/codelets/t1_12.c
  ${fftwroot}/dft/scalar/codelets/t1_15.c
  ${fftwroot}/dft/scalar/codelets/t1_16.c
  ${fftwroot}/dft/scalar/codelets/t1_2.c
  ${fftwroot}/dft/scalar/codelets/t1_20.c
  ${fftwroot}/dft/scalar/codelets/t1_25.c
  ${fftwroot}/dft/scalar/codelets/t1_3.c
  ${fftwroot}/dft/scalar/codelets/t1_32.c
  ${fftwroot}/dft/scalar/codelets/t1_4.c
  ${fftwroot}/dft/scalar/codelets/t1_5.c
  ${fftwroot}/dft/scalar/codelets/t1_6.c
  ${fftwroot}/dft/scalar/codelets/t1_64.c
  ${fftwroot}/dft/scalar/codelets/t1_7.c
  ${fftwroot}/dft/scalar/codelets/t1_8.c
  ${fftwroot}/dft/scalar/codelets/t1_9.c
  ${fftwroot}/dft/scalar/codelets/t2_10.c
  ${fftwroot}/dft/scalar/codelets/t2_16.c
  ${fftwroot}/dft/scalar/codelets/t2_20.c
  ${fftwroot}/dft/scalar/codelets/t2_25.c
  ${fftwroot}/dft/scalar/codelets/t2_32.c
  ${fftwroot}/dft/scalar/codelets/t2_4.c
  ${fftwroot}/dft/scalar/codelets/t2_5.c
  ${fftwroot}/dft/scalar/codelets/t2_64.c
  ${fftwroot}/dft/scalar/codelets/t2_8.c
  )
source_group("Source Files\\dft\\scalar\\codelets" FILES ${dft_scalar_codelets_srcs})
list(APPEND ${lib_name}_libsrcs ${dft_scalar_codelets_srcs})
#####
set(dft_simd_sse2_srcs
  ${fftwroot}/dft/simd/sse2/codlist.c
  ${fftwroot}/dft/simd/sse2/genus.c
  ${fftwroot}/dft/simd/sse2/n1bv_10.c
  ${fftwroot}/dft/simd/sse2/n1bv_11.c
  ${fftwroot}/dft/simd/sse2/n1bv_12.c
  ${fftwroot}/dft/simd/sse2/n1bv_128.c
  ${fftwroot}/dft/simd/sse2/n1bv_13.c
  ${fftwroot}/dft/simd/sse2/n1bv_14.c
  ${fftwroot}/dft/simd/sse2/n1bv_15.c
  ${fftwroot}/dft/simd/sse2/n1bv_16.c
  ${fftwroot}/dft/simd/sse2/n1bv_2.c
  ${fftwroot}/dft/simd/sse2/n1bv_20.c
  ${fftwroot}/dft/simd/sse2/n1bv_25.c
  ${fftwroot}/dft/simd/sse2/n1bv_3.c
  ${fftwroot}/dft/simd/sse2/n1bv_32.c
  ${fftwroot}/dft/simd/sse2/n1bv_4.c
  ${fftwroot}/dft/simd/sse2/n1bv_5.c
  ${fftwroot}/dft/simd/sse2/n1bv_6.c
  ${fftwroot}/dft/simd/sse2/n1bv_64.c
  ${fftwroot}/dft/simd/sse2/n1bv_7.c
  ${fftwroot}/dft/simd/sse2/n1bv_8.c
  ${fftwroot}/dft/simd/sse2/n1bv_9.c
  ${fftwroot}/dft/simd/sse2/n1fv_10.c
  ${fftwroot}/dft/simd/sse2/n1fv_11.c
  ${fftwroot}/dft/simd/sse2/n1fv_12.c
  ${fftwroot}/dft/simd/sse2/n1fv_128.c
  ${fftwroot}/dft/simd/sse2/n1fv_13.c
  ${fftwroot}/dft/simd/sse2/n1fv_14.c
  ${fftwroot}/dft/simd/sse2/n1fv_15.c
  ${fftwroot}/dft/simd/sse2/n1fv_16.c
  ${fftwroot}/dft/simd/sse2/n1fv_2.c
  ${fftwroot}/dft/simd/sse2/n1fv_20.c
  ${fftwroot}/dft/simd/sse2/n1fv_25.c
  ${fftwroot}/dft/simd/sse2/n1fv_3.c
  ${fftwroot}/dft/simd/sse2/n1fv_32.c
  ${fftwroot}/dft/simd/sse2/n1fv_4.c
  ${fftwroot}/dft/simd/sse2/n1fv_5.c
  ${fftwroot}/dft/simd/sse2/n1fv_6.c
  ${fftwroot}/dft/simd/sse2/n1fv_64.c
  ${fftwroot}/dft/simd/sse2/n1fv_7.c
  ${fftwroot}/dft/simd/sse2/n1fv_8.c
  ${fftwroot}/dft/simd/sse2/n1fv_9.c
  ${fftwroot}/dft/simd/sse2/n2bv_10.c
  ${fftwroot}/dft/simd/sse2/n2bv_12.c
  ${fftwroot}/dft/simd/sse2/n2bv_14.c
  ${fftwroot}/dft/simd/sse2/n2bv_16.c
  ${fftwroot}/dft/simd/sse2/n2bv_2.c
  ${fftwroot}/dft/simd/sse2/n2bv_20.c
  ${fftwroot}/dft/simd/sse2/n2bv_32.c
  ${fftwroot}/dft/simd/sse2/n2bv_4.c
  ${fftwroot}/dft/simd/sse2/n2bv_6.c
  ${fftwroot}/dft/simd/sse2/n2bv_64.c
  ${fftwroot}/dft/simd/sse2/n2bv_8.c
  ${fftwroot}/dft/simd/sse2/n2fv_10.c
  ${fftwroot}/dft/simd/sse2/n2fv_12.c
  ${fftwroot}/dft/simd/sse2/n2fv_14.c
  ${fftwroot}/dft/simd/sse2/n2fv_16.c
  ${fftwroot}/dft/simd/sse2/n2fv_2.c
  ${fftwroot}/dft/simd/sse2/n2fv_20.c
  ${fftwroot}/dft/simd/sse2/n2fv_32.c
  ${fftwroot}/dft/simd/sse2/n2fv_4.c
  ${fftwroot}/dft/simd/sse2/n2fv_6.c
  ${fftwroot}/dft/simd/sse2/n2fv_64.c
  ${fftwroot}/dft/simd/sse2/n2fv_8.c
  ${fftwroot}/dft/simd/sse2/n2sv_16.c
  ${fftwroot}/dft/simd/sse2/n2sv_32.c
  ${fftwroot}/dft/simd/sse2/n2sv_4.c
  ${fftwroot}/dft/simd/sse2/n2sv_64.c
  ${fftwroot}/dft/simd/sse2/n2sv_8.c
  ${fftwroot}/dft/simd/sse2/q1bv_2.c
  ${fftwroot}/dft/simd/sse2/q1bv_4.c
  ${fftwroot}/dft/simd/sse2/q1bv_5.c
  ${fftwroot}/dft/simd/sse2/q1bv_8.c
  ${fftwroot}/dft/simd/sse2/q1fv_2.c
  ${fftwroot}/dft/simd/sse2/q1fv_4.c
  ${fftwroot}/dft/simd/sse2/q1fv_5.c
  ${fftwroot}/dft/simd/sse2/q1fv_8.c
  ${fftwroot}/dft/simd/sse2/t1buv_10.c
  ${fftwroot}/dft/simd/sse2/t1buv_2.c
  ${fftwroot}/dft/simd/sse2/t1buv_3.c
  ${fftwroot}/dft/simd/sse2/t1buv_4.c
  ${fftwroot}/dft/simd/sse2/t1buv_5.c
  ${fftwroot}/dft/simd/sse2/t1buv_6.c
  ${fftwroot}/dft/simd/sse2/t1buv_7.c
  ${fftwroot}/dft/simd/sse2/t1buv_8.c
  ${fftwroot}/dft/simd/sse2/t1buv_9.c
  ${fftwroot}/dft/simd/sse2/t1bv_10.c
  ${fftwroot}/dft/simd/sse2/t1bv_12.c
  ${fftwroot}/dft/simd/sse2/t1bv_15.c
  ${fftwroot}/dft/simd/sse2/t1bv_16.c
  ${fftwroot}/dft/simd/sse2/t1bv_2.c
  ${fftwroot}/dft/simd/sse2/t1bv_20.c
  ${fftwroot}/dft/simd/sse2/t1bv_25.c
  ${fftwroot}/dft/simd/sse2/t1bv_3.c
  ${fftwroot}/dft/simd/sse2/t1bv_32.c
  ${fftwroot}/dft/simd/sse2/t1bv_4.c
  ${fftwroot}/dft/simd/sse2/t1bv_5.c
  ${fftwroot}/dft/simd/sse2/t1bv_6.c
  ${fftwroot}/dft/simd/sse2/t1bv_64.c
  ${fftwroot}/dft/simd/sse2/t1bv_7.c
  ${fftwroot}/dft/simd/sse2/t1bv_8.c
  ${fftwroot}/dft/simd/sse2/t1bv_9.c
  ${fftwroot}/dft/simd/sse2/t1fuv_10.c
  ${fftwroot}/dft/simd/sse2/t1fuv_2.c
  ${fftwroot}/dft/simd/sse2/t1fuv_3.c
  ${fftwroot}/dft/simd/sse2/t1fuv_4.c
  ${fftwroot}/dft/simd/sse2/t1fuv_5.c
  ${fftwroot}/dft/simd/sse2/t1fuv_6.c
  ${fftwroot}/dft/simd/sse2/t1fuv_7.c
  ${fftwroot}/dft/simd/sse2/t1fuv_8.c
  ${fftwroot}/dft/simd/sse2/t1fuv_9.c
  ${fftwroot}/dft/simd/sse2/t1fv_10.c
  ${fftwroot}/dft/simd/sse2/t1fv_12.c
  ${fftwroot}/dft/simd/sse2/t1fv_15.c
  ${fftwroot}/dft/simd/sse2/t1fv_16.c
  ${fftwroot}/dft/simd/sse2/t1fv_2.c
  ${fftwroot}/dft/simd/sse2/t1fv_20.c
  ${fftwroot}/dft/simd/sse2/t1fv_25.c
  ${fftwroot}/dft/simd/sse2/t1fv_3.c
  ${fftwroot}/dft/simd/sse2/t1fv_32.c
  ${fftwroot}/dft/simd/sse2/t1fv_4.c
  ${fftwroot}/dft/simd/sse2/t1fv_5.c
  ${fftwroot}/dft/simd/sse2/t1fv_6.c
  ${fftwroot}/dft/simd/sse2/t1fv_64.c
  ${fftwroot}/dft/simd/sse2/t1fv_7.c
  ${fftwroot}/dft/simd/sse2/t1fv_8.c
  ${fftwroot}/dft/simd/sse2/t1fv_9.c
  ${fftwroot}/dft/simd/sse2/t1sv_16.c
  ${fftwroot}/dft/simd/sse2/t1sv_2.c
  ${fftwroot}/dft/simd/sse2/t1sv_32.c
  ${fftwroot}/dft/simd/sse2/t1sv_4.c
  ${fftwroot}/dft/simd/sse2/t1sv_8.c
  ${fftwroot}/dft/simd/sse2/t2bv_10.c
  ${fftwroot}/dft/simd/sse2/t2bv_16.c
  ${fftwroot}/dft/simd/sse2/t2bv_2.c
  ${fftwroot}/dft/simd/sse2/t2bv_20.c
  ${fftwroot}/dft/simd/sse2/t2bv_25.c
  ${fftwroot}/dft/simd/sse2/t2bv_32.c
  ${fftwroot}/dft/simd/sse2/t2bv_4.c
  ${fftwroot}/dft/simd/sse2/t2bv_5.c
  ${fftwroot}/dft/simd/sse2/t2bv_64.c
  ${fftwroot}/dft/simd/sse2/t2bv_8.c
  ${fftwroot}/dft/simd/sse2/t2fv_10.c
  ${fftwroot}/dft/simd/sse2/t2fv_16.c
  ${fftwroot}/dft/simd/sse2/t2fv_2.c
  ${fftwroot}/dft/simd/sse2/t2fv_20.c
  ${fftwroot}/dft/simd/sse2/t2fv_25.c
  ${fftwroot}/dft/simd/sse2/t2fv_32.c
  ${fftwroot}/dft/simd/sse2/t2fv_4.c
  ${fftwroot}/dft/simd/sse2/t2fv_5.c
  ${fftwroot}/dft/simd/sse2/t2fv_64.c
  ${fftwroot}/dft/simd/sse2/t2fv_8.c
  ${fftwroot}/dft/simd/sse2/t2sv_16.c
  ${fftwroot}/dft/simd/sse2/t2sv_32.c
  ${fftwroot}/dft/simd/sse2/t2sv_4.c
  ${fftwroot}/dft/simd/sse2/t2sv_8.c
  ${fftwroot}/dft/simd/sse2/t3bv_10.c
  ${fftwroot}/dft/simd/sse2/t3bv_16.c
  ${fftwroot}/dft/simd/sse2/t3bv_20.c
  ${fftwroot}/dft/simd/sse2/t3bv_25.c
  ${fftwroot}/dft/simd/sse2/t3bv_32.c
  ${fftwroot}/dft/simd/sse2/t3bv_4.c
  ${fftwroot}/dft/simd/sse2/t3bv_5.c
  ${fftwroot}/dft/simd/sse2/t3bv_8.c
  ${fftwroot}/dft/simd/sse2/t3fv_10.c
  ${fftwroot}/dft/simd/sse2/t3fv_16.c
  ${fftwroot}/dft/simd/sse2/t3fv_20.c
  ${fftwroot}/dft/simd/sse2/t3fv_25.c
  ${fftwroot}/dft/simd/sse2/t3fv_32.c
  ${fftwroot}/dft/simd/sse2/t3fv_4.c
  ${fftwroot}/dft/simd/sse2/t3fv_5.c
  ${fftwroot}/dft/simd/sse2/t3fv_8.c
  )
source_group("Source Files\\dft\\simd\\sse2" FILES ${dft_simd_sse2_srcs})
if(HAVE_SSE2)
  list(APPEND ${lib_name}_libsrcs ${dft_simd_sse2_srcs})
endif()
########################
# kernel
set(kernel_srcs
  ${fftwroot}/kernel/align.c
  ${fftwroot}/kernel/alloc.c
  ${fftwroot}/kernel/assert.c
  ${fftwroot}/kernel/awake.c
  ${fftwroot}/kernel/buffered.c
  ${fftwroot}/kernel/cpy1d.c
  ${fftwroot}/kernel/cpy2d-pair.c
  ${fftwroot}/kernel/cpy2d.c
  ${fftwroot}/kernel/ct.c
  ${fftwroot}/kernel/debug.c
  ${fftwroot}/kernel/extract-reim.c
  ${fftwroot}/kernel/hash.c
  ${fftwroot}/kernel/iabs.c
  ${fftwroot}/kernel/kalloc.c
  ${fftwroot}/kernel/md5-1.c
  ${fftwroot}/kernel/md5.c
  ${fftwroot}/kernel/minmax.c
  ${fftwroot}/kernel/ops.c
  ${fftwroot}/kernel/pickdim.c
  ${fftwroot}/kernel/plan.c
  ${fftwroot}/kernel/planner.c
  ${fftwroot}/kernel/primes.c
  ${fftwroot}/kernel/print.c
  ${fftwroot}/kernel/problem.c
  ${fftwroot}/kernel/rader.c
  ${fftwroot}/kernel/scan.c
  ${fftwroot}/kernel/solver.c
  ${fftwroot}/kernel/solvtab.c
  ${fftwroot}/kernel/stride.c
  ${fftwroot}/kernel/tensor.c
  ${fftwroot}/kernel/tensor1.c
  ${fftwroot}/kernel/tensor2.c
  ${fftwroot}/kernel/tensor3.c
  ${fftwroot}/kernel/tensor4.c
  ${fftwroot}/kernel/tensor5.c
  ${fftwroot}/kernel/tensor7.c
  ${fftwroot}/kernel/tensor8.c
  ${fftwroot}/kernel/tensor9.c
  ${fftwroot}/kernel/tile2d.c
  ${fftwroot}/kernel/timer.c
  ${fftwroot}/kernel/transpose.c
  ${fftwroot}/kernel/trig.c
  ${fftwroot}/kernel/twiddle.c
  )
source_group("Source Files\\kernel" FILES ${kernel_srcs})
list(APPEND ${lib_name}_libsrcs ${kernel_srcs})
########################
# rdft
set(rdft_srcs
  ${fftwroot}/rdft/buffered2.c
  ${fftwroot}/rdft/buffered.c
  ${fftwroot}/rdft/conf.c
  ${fftwroot}/rdft/ct-hc2c.c
  ${fftwroot}/rdft/ct-hc2c-direct.c
  ${fftwroot}/rdft/dft-r2hc.c
  ${fftwroot}/rdft/dht-r2hc.c
  ${fftwroot}/rdft/dht-rader.c
  ${fftwroot}/rdft/direct2.c
  ${fftwroot}/rdft/direct-r2c.c
  ${fftwroot}/rdft/direct-r2r.c
  ${fftwroot}/rdft/generic.c
  ${fftwroot}/rdft/hc2hc.c
  ${fftwroot}/rdft/hc2hc-direct.c
  ${fftwroot}/rdft/hc2hc-generic.c
  ${fftwroot}/rdft/indirect.c
  ${fftwroot}/rdft/khc2c.c
  ${fftwroot}/rdft/khc2hc.c
  ${fftwroot}/rdft/kr2c.c
  ${fftwroot}/rdft/kr2r.c
  ${fftwroot}/rdft/nop2.c
  ${fftwroot}/rdft/nop.c
  ${fftwroot}/rdft/plan2.c
  ${fftwroot}/rdft/plan.c
  ${fftwroot}/rdft/problem2.c
  ${fftwroot}/rdft/problem.c
  ${fftwroot}/rdft/rank0.c
  ${fftwroot}/rdft/rank0-rdft2.c
  ${fftwroot}/rdft/rank-geq2.c
  ${fftwroot}/rdft/rank-geq2-rdft2.c
  ${fftwroot}/rdft/rdft2-inplace-strides.c
  ${fftwroot}/rdft/rdft2-rdft.c
  ${fftwroot}/rdft/rdft2-strides.c
  ${fftwroot}/rdft/rdft2-tensor-max-index.c
  ${fftwroot}/rdft/rdft-dht.c
  ${fftwroot}/rdft/solve2.c
  ${fftwroot}/rdft/solve.c
  ${fftwroot}/rdft/vrank3-transpose.c
  ${fftwroot}/rdft/vrank-geq1.c
  ${fftwroot}/rdft/vrank-geq1-rdft2.c
  )
source_group("Source Files\\rdft" FILES ${rdft_srcs})
list(APPEND ${lib_name}_libsrcs ${rdft_srcs})
#####
set(rdft_scalar_srcs
  ${fftwroot}/rdft/scalar/hc2c.c
  ${fftwroot}/rdft/scalar/hfb.c
  ${fftwroot}/rdft/scalar/r2c.c
  ${fftwroot}/rdft/scalar/r2r.c
  )
source_group("Source Files\\rdft\\scalar" FILES ${rdft_scalar_srcs})
list(APPEND ${lib_name}_libsrcs ${rdft_scalar_srcs})
#####
set(rdft_scalar_r2cb_srcs
  ${fftwroot}/rdft/scalar/r2cb/codlist.c
  ${fftwroot}/rdft/scalar/r2cb/hb_10.c
  ${fftwroot}/rdft/scalar/r2cb/hb_12.c
  ${fftwroot}/rdft/scalar/r2cb/hb_15.c
  ${fftwroot}/rdft/scalar/r2cb/hb_16.c
  ${fftwroot}/rdft/scalar/r2cb/hb_20.c
  ${fftwroot}/rdft/scalar/r2cb/hb2_16.c
  ${fftwroot}/rdft/scalar/r2cb/hb2_20.c
  ${fftwroot}/rdft/scalar/r2cb/hb2_25.c
  ${fftwroot}/rdft/scalar/r2cb/hb2_32.c
  ${fftwroot}/rdft/scalar/r2cb/hb2_4.c
  ${fftwroot}/rdft/scalar/r2cb/hb_25.c
  ${fftwroot}/rdft/scalar/r2cb/hb2_5.c
  ${fftwroot}/rdft/scalar/r2cb/hb2_8.c
  ${fftwroot}/rdft/scalar/r2cb/hb_2.c
  ${fftwroot}/rdft/scalar/r2cb/hb_32.c
  ${fftwroot}/rdft/scalar/r2cb/hb_3.c
  ${fftwroot}/rdft/scalar/r2cb/hb_4.c
  ${fftwroot}/rdft/scalar/r2cb/hb_5.c
  ${fftwroot}/rdft/scalar/r2cb/hb_64.c
  ${fftwroot}/rdft/scalar/r2cb/hb_6.c
  ${fftwroot}/rdft/scalar/r2cb/hb_7.c
  ${fftwroot}/rdft/scalar/r2cb/hb_8.c
  ${fftwroot}/rdft/scalar/r2cb/hb_9.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cb_10.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cb_12.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cb_16.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cb_20.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cb2_16.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cb2_20.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cb2_32.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cb2_4.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cb2_8.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cb_2.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cb_32.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cb_4.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cb_6.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cb_8.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cbdft_10.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cbdft_12.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cbdft_16.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cbdft_20.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cbdft2_16.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cbdft2_20.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cbdft2_32.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cbdft2_4.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cbdft2_8.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cbdft_2.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cbdft_32.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cbdft_4.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cbdft_6.c
  ${fftwroot}/rdft/scalar/r2cb/hc2cbdft_8.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_10.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_11.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_128.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_12.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_13.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_14.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_15.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_16.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_20.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_25.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_2.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_32.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_3.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_4.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_5.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_64.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_6.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_7.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_8.c
  ${fftwroot}/rdft/scalar/r2cb/r2cb_9.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_10.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_12.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_15.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_16.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_20.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_25.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_2.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_32.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_3.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_4.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_5.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_64.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_6.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_7.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_8.c
  ${fftwroot}/rdft/scalar/r2cb/r2cbIII_9.c
  )
source_group("Source Files\\rdft\\scalar\\r2cb" FILES ${rdft_scalar_r2cb_srcs})
list(APPEND ${lib_name}_libsrcs ${rdft_scalar_r2cb_srcs})
#####
set(rdft_scalar_r2cf_srcs
  ${fftwroot}/rdft/scalar/r2cf/codlist.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cf_10.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cf_12.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cf_16.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cf_20.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cf2_16.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cf2_20.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cf2_32.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cf2_4.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cf2_8.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cf_2.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cf_32.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cf_4.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cf_6.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cf_8.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cfdft_10.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cfdft_12.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cfdft_16.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cfdft_20.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cfdft2_16.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cfdft2_20.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cfdft2_32.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cfdft2_4.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cfdft2_8.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cfdft_2.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cfdft_32.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cfdft_4.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cfdft_6.c
  ${fftwroot}/rdft/scalar/r2cf/hc2cfdft_8.c
  ${fftwroot}/rdft/scalar/r2cf/hf_10.c
  ${fftwroot}/rdft/scalar/r2cf/hf_12.c
  ${fftwroot}/rdft/scalar/r2cf/hf_15.c
  ${fftwroot}/rdft/scalar/r2cf/hf_16.c
  ${fftwroot}/rdft/scalar/r2cf/hf_20.c
  ${fftwroot}/rdft/scalar/r2cf/hf2_16.c
  ${fftwroot}/rdft/scalar/r2cf/hf2_20.c
  ${fftwroot}/rdft/scalar/r2cf/hf2_25.c
  ${fftwroot}/rdft/scalar/r2cf/hf2_32.c
  ${fftwroot}/rdft/scalar/r2cf/hf2_4.c
  ${fftwroot}/rdft/scalar/r2cf/hf_25.c
  ${fftwroot}/rdft/scalar/r2cf/hf2_5.c
  ${fftwroot}/rdft/scalar/r2cf/hf2_8.c
  ${fftwroot}/rdft/scalar/r2cf/hf_2.c
  ${fftwroot}/rdft/scalar/r2cf/hf_32.c
  ${fftwroot}/rdft/scalar/r2cf/hf_3.c
  ${fftwroot}/rdft/scalar/r2cf/hf_4.c
  ${fftwroot}/rdft/scalar/r2cf/hf_5.c
  ${fftwroot}/rdft/scalar/r2cf/hf_64.c
  ${fftwroot}/rdft/scalar/r2cf/hf_6.c
  ${fftwroot}/rdft/scalar/r2cf/hf_7.c
  ${fftwroot}/rdft/scalar/r2cf/hf_8.c
  ${fftwroot}/rdft/scalar/r2cf/hf_9.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_10.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_11.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_128.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_12.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_13.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_14.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_15.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_16.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_20.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_25.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_2.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_32.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_3.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_4.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_5.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_64.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_6.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_7.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_8.c
  ${fftwroot}/rdft/scalar/r2cf/r2cf_9.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_10.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_12.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_15.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_16.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_20.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_25.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_2.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_32.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_3.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_4.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_5.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_64.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_6.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_7.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_8.c
  ${fftwroot}/rdft/scalar/r2cf/r2cfII_9.c
  )
source_group("Source Files\\rdft\\scalar\\r2cf" FILES ${rdft_scalar_r2cf_srcs})
list(APPEND ${lib_name}_libsrcs ${rdft_scalar_r2cf_srcs})
#####
set(rdft_scalar_r2r_srcs
  ${fftwroot}/rdft/scalar/r2r/codlist.c
  ${fftwroot}/rdft/scalar/r2r/e01_8.c
  ${fftwroot}/rdft/scalar/r2r/e10_8.c
  )
source_group("Source Files\\rdft\\scalar\\r2r" FILES ${rdft_scalar_r2r_srcs})
list(APPEND ${lib_name}_libsrcs ${rdft_scalar_r2r_srcs})
#####
set(rdft_simd_sse2_srcs
  ${fftwroot}/rdft/simd/sse2/codlist.c
  ${fftwroot}/rdft/simd/sse2/genus.c
  ${fftwroot}/rdft/simd/sse2/hc2cbdftv_10.c
  ${fftwroot}/rdft/simd/sse2/hc2cbdftv_12.c
  ${fftwroot}/rdft/simd/sse2/hc2cbdftv_16.c
  ${fftwroot}/rdft/simd/sse2/hc2cbdftv_20.c
  ${fftwroot}/rdft/simd/sse2/hc2cbdftv_2.c
  ${fftwroot}/rdft/simd/sse2/hc2cbdftv_32.c
  ${fftwroot}/rdft/simd/sse2/hc2cbdftv_4.c
  ${fftwroot}/rdft/simd/sse2/hc2cbdftv_6.c
  ${fftwroot}/rdft/simd/sse2/hc2cbdftv_8.c
  ${fftwroot}/rdft/simd/sse2/hc2cfdftv_10.c
  ${fftwroot}/rdft/simd/sse2/hc2cfdftv_12.c
  ${fftwroot}/rdft/simd/sse2/hc2cfdftv_16.c
  ${fftwroot}/rdft/simd/sse2/hc2cfdftv_20.c
  ${fftwroot}/rdft/simd/sse2/hc2cfdftv_2.c
  ${fftwroot}/rdft/simd/sse2/hc2cfdftv_32.c
  ${fftwroot}/rdft/simd/sse2/hc2cfdftv_4.c
  ${fftwroot}/rdft/simd/sse2/hc2cfdftv_6.c
  ${fftwroot}/rdft/simd/sse2/hc2cfdftv_8.c
  )
source_group("Source Files\\rdft\\simd\\sse2" FILES ${rdft_simd_sse2_srcs})
if(HAVE_SSE2)
  list(APPEND ${lib_name}_libsrcs ${rdft_simd_sse2_srcs})
endif()
########################
# reodft
set(reodft_srcs
  ${fftwroot}/reodft/conf.c
  ${fftwroot}/reodft/redft00e-r2hc.c
  ${fftwroot}/reodft/redft00e-r2hc-pad.c
  ${fftwroot}/reodft/reodft00e-splitradix.c
  ${fftwroot}/reodft/reodft010e-r2hc.c
  ${fftwroot}/reodft/reodft11e-r2hc.c
  ${fftwroot}/reodft/reodft11e-r2hc-odd.c
  ${fftwroot}/reodft/reodft11e-radix2.c
  ${fftwroot}/reodft/rodft00e-r2hc.c
  ${fftwroot}/reodft/rodft00e-r2hc-pad.c
  )
source_group("Source Files\\reodft" FILES ${reodft_srcs})
list(APPEND ${lib_name}_libsrcs ${reodft_srcs})
########################
# simd-support
set(simdsupport_srcs
  ${fftwroot}/simd-support/sse2.c
  ${fftwroot}/simd-support/sse2-nonportable.c
  ${fftwroot}/simd-support/taint.c
  )
source_group("Source Files\\simd-support" FILES ${simdsupport_srcs})
if(HAVE_SSE2)
  list(APPEND ${lib_name}_libsrcs ${simdsupport_srcs})
endif()
########################
# threads
set(threads_src
  ${fftwroot}/threads/api.c
  ${fftwroot}/threads/conf.c
  ${fftwroot}/threads/ct.c
  ${fftwroot}/threads/dft-vrank-geq1.c
  ${fftwroot}/threads/f77api.c
  ${fftwroot}/threads/hc2hc.c
  ${fftwroot}/threads/openmp.c
  ${fftwroot}/threads/rdft-vrank-geq1.c
  #${fftwroot}/threads/threads.c
  ${fftwroot}/threads/vrank-geq1-rdft2.c
  )
source_group("Source Files\\threads" FILES ${threads_srcs})
list(APPEND ${lib_name}_libsrcs ${threads_srcs})
#######################################
# library
add_library(${lib_name} STATIC ${${lib_name}_libsrcs})
